import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Inknut_Antiqua } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";

const inknutAntiqua = Inknut_Antiqua({ weight: "400", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inknutAntiqua.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}